
name: flutter_test1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf

  assets:
    - assets/finni_background.jpg
    - assets/audio/background_music.mp3
    - assets/audio/buying_sound.mp3
    - assets/audio/lwl_sound.mp3
    - assets/audio/eating_sound.mp3
    - assets/tasts_background.png
    - assets/coin.png
    - assets/dino_paw_blue.png
    - assets/dino_paw_gray.png
    - assets/dino/

flutter_launcher_icons:
  android: true
  windows:
    generate: true
    image_path: "assets/coin.png"
    icon_size: 48
  image_path: "assets/coin.png"